# Site metadata.

# Canonical URL
url: https://pulse.cio.gov

name: Pulse
title: "The pulse of the federal .gov space"
description: "How federal government domains are meeting best practices on the web."

# When the data we used was generated. Manually updated for now.
data:
  # The scan date.
  scan: 2016-01-23

  # URL where we download the .gov domain list from.
  domains_url: https://raw.githubusercontent.com/GSA/data/gh-pages/dotgov-domains/2016-01-19-federal.csv

  # The export date for the .gov domain list. Increasingly non-relevant.
  domains: 2015-11-03
